import { Suspense } from "react"
import BrowseClient from "./BrowseClient"
import { Header } from "@/components/header"

const venuesData = [
  {
    id: 1,
    nameKey: "Skyline Penthouse",
    locationKey: "Vake, Tbilisi",
    price: 450,
    guests: 30,
    sqm: 320,
    image: "/images/venues/skyline-penthouse.jpg",
    images: [
      "/images/venues/skyline-penthouse.jpg",
      "/images/venues/mountain-retreat.jpg",
      "/images/venues/rooftop-terrace.jpg",
      "/images/venues/garden-villa.jpg",
      "/images/venues/seaside-villa.jpg",
    ],
    description: "Luxury penthouse with city views",
    amenities: ["wifi", "kitchen", "heating"],
    location: "Vake, Tbilisi",
    premium: true,
    category: "rooftops" as const,
  },
  {
    id: 2,
    nameKey: "Garden Villa",
    locationKey: "Saburtalo, Tbilisi",
    price: 680,
    guests: 50,
    sqm: 450,
    image: "/images/venues/garden-villa.jpg",
    images: [
      "/images/venues/garden-villa.jpg",
      "/images/venues/skyline-penthouse.jpg",
      "/images/venues/seaside-villa.jpg",
      "/images/venues/rooftop-terrace.jpg",
      "/images/venues/loft-studio.jpg",
    ],
    description: "Beautiful garden villa with spacious grounds",
    amenities: ["wifi", "kitchen", "pool", "parking"],
    location: "Saburtalo, Tbilisi",
    premium: true,
    category: "villas" as const,
  },
  {
    id: 3,
    nameKey: "Rooftop Terrace",
    locationKey: "Old Town, Tbilisi",
    price: 320,
    guests: 25,
    sqm: 200,
    image: "/images/venues/rooftop-terrace.jpg",
    images: [
      "/images/venues/rooftop-terrace.jpg",
      "/images/venues/seaside-villa.jpg",
      "/images/venues/skyline-penthouse.jpg",
      "/images/venues/garden-villa.jpg",
      "/images/venues/mountain-retreat.jpg",
    ],
    description: "Charming rooftop terrace in historic old town",
    amenities: ["wifi", "heating"],
    location: "Old Town, Tbilisi",
    premium: true,
    category: "rooftops" as const,
  },
  {
    id: 4,
    nameKey: "Loft Studio",
    locationKey: "Vera, Tbilisi",
    price: 280,
    guests: 20,
    sqm: 180,
    image: "/images/venues/loft-studio.jpg",
    images: [
      "/images/venues/loft-studio.jpg",
      "/images/venues/skyline-penthouse.jpg",
      "/images/venues/garden-villa.jpg",
      "/images/venues/seaside-villa.jpg",
      "/images/venues/rooftop-terrace.jpg",
    ],
    description: "Modern loft studio with contemporary design",
    amenities: ["wifi", "kitchen", "heating"],
    location: "Vera, Tbilisi",
    premium: false,
    category: "modern" as const,
  },
  {
    id: 5,
    nameKey: "Modern Glass House",
    locationKey: "Didi Dighomi, Tbilisi",
    price: 550,
    guests: 40,
    sqm: 380,
    image: "/images/venues/seaside-villa.jpg",
    images: [
      "/images/venues/seaside-villa.jpg",
      "/images/venues/mountain-retreat.jpg",
      "/images/venues/skyline-penthouse.jpg",
      "/images/venues/garden-villa.jpg",
      "/images/venues/rooftop-terrace.jpg",
    ],
    description: "Stunning modern glass house with panoramic views",
    amenities: ["wifi", "kitchen", "pool", "parking"],
    location: "Didi Dighomi, Tbilisi",
    premium: false,
    category: "modern" as const,
  },
  {
    id: 6,
    nameKey: "Panorama Villa",
    locationKey: "Mtskheta",
    price: 420,
    guests: 30,
    sqm: 260,
    image: "/images/venues/mountain-retreat.jpg",
    images: [
      "/images/venues/mountain-retreat.jpg",
      "/images/venues/seaside-villa.jpg",
      "/images/venues/skyline-penthouse.jpg",
      "/images/venues/garden-villa.jpg",
      "/images/venues/loft-studio.jpg",
    ],
    description: "Beautiful villa with stunning mountain panorama",
    amenities: ["wifi", "heating", "parking"],
    location: "Mtskheta",
    premium: false,
    category: "villas" as const,
  },
  {
    id: 7,
    nameKey: "Event Hall One",
    locationKey: "Saburtalo, Tbilisi",
    price: 1200,
    guests: 100,
    sqm: 600,
    image: "/images/venues/garden-villa.jpg",
    images: [
      "/images/venues/garden-villa.jpg",
      "/images/venues/skyline-penthouse.jpg",
    ],
    description: "Premium event hall for large gatherings",
    amenities: ["wifi", "kitchen", "parking", "heating"],
    location: "Saburtalo, Tbilisi",
    premium: false,
    category: "event" as const,
  },
  {
    id: 8,
    nameKey: "Poolside Paradise",
    locationKey: "Kojori",
    price: 350,
    guests: 25,
    sqm: 210,
    image: "/images/venues/rooftop-terrace.jpg",
    images: [
      "/images/venues/rooftop-terrace.jpg",
      "/images/venues/seaside-villa.jpg",
    ],
    description: "Relaxing poolside retreat in the mountains",
    amenities: ["wifi", "pool", "parking"],
    location: "Kojori",
    premium: false,
    category: "outdoor" as const,
  },
]

export default function BrowsePage() {
  return (
    <main className="min-h-screen bg-[#EEF3F8] relative">
      <Header />
      <Suspense fallback={<div className="pt-24 px-6">Loading venues...</div>}>
        <BrowseClient venuesData={venuesData} />
      </Suspense>
    </main>
  )
}
