export const staticVenuesData = [
  {
    id: 1,
    nameKey: "skylinePenthouse" as const,
    locationKey: "vakeTbilisi" as const,
    price: 450,
    guests: 30,
    latitude: 41.7189,
    longitude: 44.7714,
    image: "/images/venues/skyline-penthouse.jpg",
    images: [
      "/images/venues/skyline-penthouse.jpg",
      "/images/venues/mountain-retreat.jpg",
      "/images/venues/rooftop-terrace.jpg",
      "/images/venues/garden-villa.jpg",
      "/images/venues/seaside-villa.jpg",
    ],
    description: "Modern penthouse with stunning city views",
    amenities: ["wifi", "kitchen", "heating"],
    premium: true,
  },
  {
    id: 2,
    nameKey: "gardenVilla" as const,
    locationKey: "saburtaloTbilisi" as const,
    price: 680,
    guests: 50,
    latitude: 41.7372,
    longitude: 44.7654,
    image: "/images/venues/garden-villa.jpg",
    images: [
      "/images/venues/garden-villa.jpg",
      "/images/venues/skyline-penthouse.jpg",
      "/images/venues/seaside-villa.jpg",
      "/images/venues/rooftop-terrace.jpg",
      "/images/venues/loft-studio.jpg",
    ],
    description: "Spacious villa with beautiful garden",
    amenities: ["wifi", "kitchen", "heating"],
    premium: true,
  },
  {
    id: 3,
    nameKey: "rooftopTerrace" as const,
    locationKey: "oldTownTbilisi" as const,
    price: 320,
    guests: 25,
    latitude: 41.7142,
    longitude: 44.8127,
    image: "/images/venues/rooftop-terrace.jpg",
    images: [
      "/images/venues/rooftop-terrace.jpg",
      "/images/venues/seaside-villa.jpg",
      "/images/venues/skyline-penthouse.jpg",
      "/images/venues/garden-villa.jpg",
      "/images/venues/mountain-retreat.jpg",
    ],
    description: "Charming rooftop with panoramic views",
    amenities: ["wifi", "kitchen", "heating"],
    premium: false,
  },
  {
    id: 4,
    nameKey: "loftStudio" as const,
    locationKey: "veraTbilisi" as const,
    price: 280,
    guests: 20,
    latitude: 41.7415,
    longitude: 44.7952,
    image: "/images/venues/loft-studio.jpg",
    images: [
      "/images/venues/loft-studio.jpg",
      "/images/venues/skyline-penthouse.jpg",
      "/images/venues/garden-villa.jpg",
      "/images/venues/seaside-villa.jpg",
      "/images/venues/rooftop-terrace.jpg",
    ],
    description: "Contemporary loft space with industrial design",
    amenities: ["wifi", "kitchen", "heating"],
    premium: false,
  },
  {
    id: 5,
    nameKey: "seasideVilla" as const,
    locationKey: "batumi" as const,
    price: 890,
    guests: 60,
    latitude: 41.6342,
    longitude: 41.6297,
    image: "/images/venues/seaside-villa.jpg",
    images: [
      "/images/venues/seaside-villa.jpg",
      "/images/venues/mountain-retreat.jpg",
      "/images/venues/skyline-penthouse.jpg",
      "/images/venues/garden-villa.jpg",
      "/images/venues/rooftop-terrace.jpg",
    ],
    description: "Luxury seaside villa with private beach access",
    amenities: ["wifi", "kitchen", "heating"],
    premium: true,
  },
  {
    id: 6,
    nameKey: "mountainRetreat" as const,
    locationKey: "borjomi" as const,
    price: 520,
    guests: 35,
    latitude: 41.8547,
    longitude: 43.4089,
    image: "/images/venues/mountain-retreat.jpg",
    images: [
      "/images/venues/mountain-retreat.jpg",
      "/images/venues/seaside-villa.jpg",
      "/images/venues/skyline-penthouse.jpg",
      "/images/venues/garden-villa.jpg",
      "/images/venues/loft-studio.jpg",
    ],
    description: "Peaceful mountain retreat surrounded by nature",
    amenities: ["wifi", "kitchen", "heating"],
    premium: false,
  },
]
